#!/usr/bin/env python3
"""
Möbius Function Analysis for Gaussian Integers
Generates figures from the tables produced by the C++ sieve.

Expected input files (generated by the C++ program):
- table1_summatory.csv      : columns: X, S(X), S(X)/sqrt(X), (log X)^2
- table2_autocorr.csv       : columns: X, C(X), C(X)/X, C(X)/X^0.85
- table3_distribution.csv   : columns: mu, Observed, Theoretical

Output:
- figure1_summatory.pdf
- figure2_autocorrelation.pdf
- figure3_distribution.pdf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# ============================================================================
# CONFIGURATION
# ============================================================================
sns.set_theme(style="whitegrid", context="paper", font_scale=1.2)
plt.rcParams['figure.dpi'] = 150
plt.rcParams['savefig.dpi'] = 300
plt.rcParams['savefig.bbox'] = 'tight'

# ============================================================================
# FIGURE 1: Summatory function S(X) / sqrt(X) vs sqrt(X)
# ============================================================================
def plot_summatory(csv_path, output_path):
    df = pd.read_csv(csv_path)
    # Columns: X, S(X), S(X)/sqrt(X), (log X)^2
    X = df['X'].values
    S_sqrtX = df['S(X)/sqrt(X)'].values
    sqrtX = np.sqrt(X)

    plt.figure(figsize=(8, 5))
    sns.scatterplot(x=sqrtX, y=S_sqrtX, s=80, color='blue', label='Data')
    sns.lineplot(x=sqrtX, y=S_sqrtX, color='blue', alpha=0.7, linewidth=1.5)
    plt.axhline(y=0, color='red', linestyle='--', alpha=0.7, label='Zero line')
    plt.xlabel(r'$\sqrt{X}$', fontsize=12)
    plt.ylabel(r'$S(X) / \sqrt{X}$', fontsize=12)
    plt.title(r'Summatory Function of Möbius in $\mathbb{Z}[i]$', fontsize=14, fontweight='bold')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_path)
    plt.close()
    print(f"Saved: {output_path}")

# ============================================================================
# FIGURE 2: Autocorrelation sum C(X) / X^{0.85} vs X (log scale)
# ============================================================================
def plot_autocorrelation(csv_path, output_path):
    df = pd.read_csv(csv_path)
    # Columns: X, C(X), C(X)/X, C(X)/X^0.85
    X = df['X'].values
    ratio = df['C(X)/X^0.85'].values

    plt.figure(figsize=(8, 5))
    sns.scatterplot(x=X, y=ratio, s=80, color='green', label='Data')
    sns.lineplot(x=X, y=ratio, color='green', alpha=0.7, linewidth=1.5)
    plt.axhline(y=0, color='red', linestyle='--', alpha=0.7, label='Zero line')
    plt.xscale('log')
    plt.xlabel(r'$X$ (log scale)', fontsize=12)
    plt.ylabel(r'$C(X) / X^{0.85}$', fontsize=12)
    plt.title(r'Autocorrelation Sum $C(X)$ for Shift $h=1$', fontsize=14, fontweight='bold')
    plt.legend()
    plt.grid(True, alpha=0.3, which='both')
    plt.tight_layout()
    plt.savefig(output_path)
    plt.close()
    print(f"Saved: {output_path}")

# ============================================================================
# FIGURE 3: Distribution of μ values (bar chart with observed vs theoretical)
# ============================================================================
def plot_distribution(csv_path, output_path):
    df = pd.read_csv(csv_path)
    # Columns: mu, Observed, Theoretical
    mu_labels = df['mu'].tolist()
    observed = df['Observed'].tolist()
    theoretical = df['Theoretical'].tolist()

    x = np.arange(len(mu_labels))
    width = 0.35

    plt.figure(figsize=(8, 6))
    bars1 = plt.bar(x - width/2, observed, width, label='Observed', color='steelblue', alpha=0.8)
    bars2 = plt.bar(x + width/2, theoretical, width, label='Theoretical', color='coral', alpha=0.8)

    plt.ylabel('Proportion', fontsize=12)
    plt.title(r'Distribution of Möbius Values in $\mathbb{Z}[i]$', fontsize=14, fontweight='bold')
    plt.xticks(x, [r'$\mu=0$', r'$\mu=+1$', r'$\mu=-1$'])
    plt.legend()

    # Add value labels on bars
    for bar in bars1:
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2., height + 0.005,
                 f'{height:.4f}', ha='center', va='bottom', fontsize=9)
    for bar in bars2:
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2., height + 0.005,
                 f'{height:.4f}', ha='center', va='bottom', fontsize=9)

    plt.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_path)
    plt.close()
    print(f"Saved: {output_path}")

# ============================================================================
# MAIN
# ============================================================================
def main():
    # Define file paths (adjust if your files are in a different directory)
    data_dir = Path('.')   # current directory, change if needed
    summatory_file = data_dir / 'table1_summatory.csv'
    autocorr_file = data_dir / 'table2_autocorr.csv'
    distribution_file = data_dir / 'table3_distribution.csv'

    # Check that all required files exist
    for f in [summatory_file, autocorr_file, distribution_file]:
        if not f.exists():
            print(f"Error: Required file not found: {f}")
            print("Please ensure the C++ program has generated all tables.")
            return

    # Create output directory for figures
    out_dir = Path('figures')
    out_dir.mkdir(exist_ok=True)

    print("=" * 60)
    print("Generating figures from C++ tables")
    print("=" * 60)

    plot_summatory(summatory_file, out_dir / 'figure1_summatory.pdf')
    plot_autocorrelation(autocorr_file, out_dir / 'figure2_autocorrelation.pdf')
    plot_distribution(distribution_file, out_dir / 'figure3_distribution.pdf')

    print("\nAll figures saved in:", out_dir)

if __name__ == '__main__':
    main()